version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  shorten:
    build: .
    container_name: shorten
    command: ./bin/shorten
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redirect:
    build: .
    container_name: redirect
    command: ./bin/redirect
    ports:
      - "8081:8081"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  stats:
    build: .
    container_name: stats
    command: ./bin/stats
    ports:
      - "8082:8082"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
