openapi: 3.0.0
info:
  title: Short URL Service API
  description: API documentation for Shorten, Redirect, and Stats services
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Shorten Service
  - url: http://localhost:8081
    description: Redirect Service
  - url: http://localhost:8082
    description: Stats Service

paths:
  /api/v1/shorten:
    post:
      summary: Generate a short URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  example: https://example.com/very/long/url
      responses:
        "200":
          description: Shortened URL created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  short_url:
                    type: string

  /{code}:
    get:
      summary: Redirect to original URL
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        "302":
          description: Redirect to original URL

  /api/v1/stats/{code}:
    get:
      summary: Get visit count of a short URL
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Visit statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  visits:
                    type: integer
